#include <iostream>
#include <fstream>
#include "CodeGenerator.h"

using namespace std;

/********************************************************************************/
/* This function will create a .cpp file with the same name as the scheme	*/
/* file provided, then add the necessary code to the beginning of the file      */
/********************************************************************************/
CodeGen::CodeGen (string filename)
{
	string cppname = filename.substr (0, filename.length()-3) + ".cpp"; 
	cpp.open (cppname.c_str());
	cpp << "// Autogenerated Scheme to C++ Code\n";
	cpp << "// File: " << cppname << "\n";
	cpp << "#include <iostream>\n";
	cpp << "#include \"Object.h\"\n";
	cpp << "using namespace std;\n\n";
}

/********************************************************************************/
/* This function will close the .cpp file					*/
/********************************************************************************/
CodeGen::~CodeGen ()
{
	cpp.close();
}

/********************************************************************************/
/* This function will take as arguments the number of tabs and the string of    */
/* code that you would like to be written to the .cpp file, then write it to    */
/* the file                                                                     */
/********************************************************************************/
void CodeGen::WriteCode (int tabs, string code)
{
	for (int t = 0; t < tabs; t++)
		cpp << '\t';
	cpp << code;
}
