// Autogenerated Scheme to C++ Code
// File: P3T1-1.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object add(, l1, l2)
{
	if(((!(nullp(l1())) && (!(nullp(l2()))))
	{
		if(((listp(l1()) && (listp(l2())))
		{
(cons (car (l1()))(cdr (l2())))		}
		else
{
			("add_requires_not_null_lists")		}
	}
	else
{
		("add_requires_not_null_lists")	}
;
}

Object multiply(, num1, num2)
{
	if(((zerop(num1()) || (zerop(num2())))
	{
		("multiply_requires_non_zero_numbers")	}
	else
{
(num1() * num2())	}
;
}

int main()
{
cout << add(("1	("1")	("2")	("3")	("4")	("5"))("a	("a")	("b")	("c")	("d")	("e")));
	cout << endl;
cout << multiply(Object(21)Object(13));
	cout << endl;
}

