// Autogenerated Scheme to C++ Code
// File: rand.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object other()
{
	Object(4);
}

int main()
{
	cout << (Object(12) + Object(5));
	cout << endl;
	cout << (Object("abc") + Object("xyz"));
	cout << endl;
	cout << (Object("abc") + Object(5));
	cout << endl;
}

